manifest:
  defaults:
    revision: main
    remote: app
  
  group-filter: [-group_zephyr, +group_forvia]

  remotes:
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos

    - name: app
      url-base: https://github.com/vpovse

  projects:
    - name: test-manifest
      remote: app
      path: application/test
      description: |
        "New project"
      groups: 
        - group_forvia

    - name: hal_nxp
      remote: zephyrproject
      clone-depth: 1
      path: extras/hal_nxp
      revision: master
      groups: 
        - group_zephyr

    - name: zephyr
      remote: zephyrproject
      clone-depth: 1
      path: extras/zephyr
      #import: true
      groups: 
        - group_zephyr
      
  self:
    path: test-zephyr

