manifest: 
  defaults:
    revision: main
    remote: gerrit_zephyr
  
  group-filter: [+group_zephyr, +group_app]

  remotes: 
    - name: gerrit_zephyr
      url-base: https://povseval@gerrit.pfa.fr.corp/a/os/zephyr
  
  projects: 
    - name: lips
      path: app
      groups: 
        - group_app

    - name: zephyr
      path: zephyrproject
      revision: zephyr_3.05.99
      groups:
        - group_zephyr

    - name: sdk
      path: /sdk_zephyr
      revision: zephyr-sdk-0.16.3
      groups:
        - group_zephyr
    
  self:
    path: test-zephyr 
