manifest: 
  defaults:
    revision: main
    remote: gerrit_zephyr
  
  group-filter: [+group_zephyr, +group_app]

  remotes: 
    - name: gerrit_zephyr
      url-base: ssh://gerrit.pfa.fr.corp:29418/os/zephyr
  
  projects: 
    - name: zephyr
      revision: zephyr_3.5.0
      groups:
        - group_zephyr
    
    - name: lips
      path: zephyr/zephyrproject/zephyr/app
      revision: master
      groups: 
        - group_app
    
  self:
    path: manifest
