manifest: 
  defaults:
    revision: main
    remote: gerrit_zephyr
  
  group-filter: [+group_zephyr, +group_app]

  remotes: 
    - name: gerrit_zephyr
      url-base: ssh://gerrit.pfa.fr.corp:29418/os/zephyr
    - name: git_zephyr
      url-base: https://github.com/zephyrproject-rtos/zephyr
  
  projects: 
    - name: zephyr
      revision: zephyr_3.5.0
      groups:
        - group_zephyr
    
    - name: lips
      path: zephyr/zephyrproject/zephyr/app
      revision: master
      groups: 
        - group_app
    - name: misc
      remote: git_zephyr
      path: zephyr/zephyrproject/zephyr/misc
      revision: zephyr_3.5.0
      groups:
        - group_zephy
    
  self:
    path: manifest
