manifest: 
  defaults:
    revision: main
    remote: gerrit_zephyr
  
  group-filter: [+group_zephyr, +group_app]

  remotes: 
    - name: gerrit_zephyr
      url-base: ssh://gerrit.pfa.fr.corp:29418/os/zephyr
    - name: git_zephyr
      url-base: https://github.com/zephyrproject-rtos/
  
  projects: 
    - name: zephyr
      revision: zephyr_3.5.0
      groups:
        - group_zephyr
    
    - name: lips
      path: zephyr/zephyrproject/zephyr/app
      revision: master
      groups: 
        - group_app
    - name: edtt
      remote: git_zephyr
      path: zephyr/zephyrproject/tools/edtt
      groups:
        - group_zephyr
        
    - name: net-tools
      remote: git_zephyr
      path: zephyr/zephyrproject/tools/net-tools
      revision: master
      groups:
        - group_zephyr

    - name: nrf_hw_models
      remote: git_zephyr
      path: zephyr/zephyrproject/modules/bsim_hw_models
      revision: master
      groups:
        - group_zephyr
    
    
  self:
    path: manifest
